### ISSUE TITLE
Server crashes on install (illegal @OnlyIn annotation in Main.java)

### ISSUE THREAD

**Issue by Refu91** [DroidDude/fltpot#14]
My server crashes when i start up with Fltpot in it.

[23:09:04] [modloading-worker-0/ERROR] [ne.mi.fm.ja.FMLModContainer/LOADING]: Failed to create mod instance. ModID: fltpot, class com.github.droiddude.fltpot.Main

**Comment by DroidDude** [comment]
It would be awesome if you could attach the crash report. Thanks!

**Comment by Refu91** [comment]
Where do i find that? xD

**Comment by Refu91** [comment]
---- Minecraft Crash Report ----
// Surprise! Haha. Well, this is awkward.

Time: 2024-06-22 23:23:05
Description: Mod loading error has occurred

java.lang.Exception: Mod Loading has failed
	at TRANSFORMER/forge@50.1.7/net.minecraftforge.logging.CrashReportExtender.dumpModLoadingCrashReport(CrashReportExtender.java:48) ~[forge-1.20.6-50.1.7-universal.jar:?] {re:classloading}
	at TRANSFORMER/forge@50.1.7/net.minecraftforge.server.loading.ServerModLoader.load(ServerModLoader.java:37) ~[forge-1.20.6-50.1.7-universal.jar:?] {re:classloading}
	at TRANSFORMER/minecraft@1.20.6/net.minecraft.server.Main.main(Main.java:127) ~[forge-1.20.6-50.1.7-server.jar:?] {re:classloading}
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?] {}
	at java.base/java.lang.reflect.Method.invoke(Method.java:580) ~[?:?] {}
	at SECURE-BOOTSTRAP/net.minecraftforge.fmlloader@1.20.6-50.1.7/net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:91) ~[fmlloader-1.20.6-50.1.7.jar!/:?] {}
	at SECURE-BOOTSTRAP/net.minecraftforge.fmlloader@1.20.6-50.1.7/net.minecraftforge.fml.loading.targets.CommonLaunchHandler.lambda$makeService$0(CommonLaunchHandler.java:75) ~[fmlloader-1.20.6-50.1.7.jar!/:?] {}
	at SECURE-BOOTSTRAP/cpw.mods.modlauncher@10.2.1/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:77) [modlauncher-10.2.1.jar!/:?] {}
	at SECURE-BOOTSTRAP/cpw.mods.modlauncher@10.2.1/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:97) [modlauncher-10.2.1.jar!/:?] {}
	at SECURE-BOOTSTRAP/cpw.mods.modlauncher@10.2.1/cpw.mods.modlauncher.Launcher.run(Launcher.java:116) [modlauncher-10.2.1.jar!/:?] {}
	at SECURE-BOOTSTRAP/cpw.mods.modlauncher@10.2.1/cpw.mods.modlauncher.Launcher.main(Launcher.java:75) [modlauncher-10.2.1.jar!/:?] {}
	at SECURE-BOOTSTRAP/cpw.mods.modlauncher@10.2.1/cpw.mods.modlauncher.BootstrapEntry.main(BootstrapEntry.java:17) [modlauncher-10.2.1.jar!/:?] {}
	at net.minecraftforge.bootstrap@2.1.3/net.minecraftforge.bootstrap.Bootstrap.moduleMain(Bootstrap.java:188) [bootstrap-2.1.3.jar!/:?] {}
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?] {}
	at java.base/java.lang.reflect.Method.invoke(Method.java:580) ~[?:?] {}
	at net.minecraftforge.bootstrap.Bootstrap.bootstrapMain(Bootstrap.java:133) [bootstrap-2.1.3.jar:2.1.3] {}
	at net.minecraftforge.bootstrap.Bootstrap.start(Bootstrap.java:53) [bootstrap-2.1.3.jar:2.1.3] {}
	at net.minecraftforge.bootstrap.ForgeBootstrap.main(ForgeBootstrap.java:19) [bootstrap-2.1.3.jar:2.1.3] {}
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?] {}
	at java.base/java.lang.reflect.Method.invoke(Method.java:580) ~[?:?] {}
	at net.minecraftforge.bootstrap.shim.Main.main(Main.java:97) [server.jar:2.1.3] {}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: main
Suspected Mods: NONE
Stacktrace:
	at cpw.mods.securejarhandler/net.minecraftforge.securemodules.SecureModuleClassLoader.loadClass(SecureModuleClassLoader.java:454) ~[securemodules-2.2.19.jar!/:?] {}
-- MOD fltpot --
Details:
	Caused by 0: java.lang.NoClassDefFoundError: net/minecraft/client/renderer/entity/RenderLayerParent
		at java.base/java.lang.Class.getDeclaredConstructors0(Native Method) ~[?:?] {re:mixin}
		at java.base/java.lang.Class.privateGetDeclaredConstructors(Class.java:3549) ~[?:?] {re:mixin}
		at java.base/java.lang.Class.getConstructor0(Class.java:3754) ~[?:?] {re:mixin}
		at java.base/java.lang.Class.getDeclaredConstructor(Class.java:2930) ~[?:?] {re:mixin}
		at LAYER PLUGIN/net.minecraftforge.javafmlmod@1.20.6-50.1.7/net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:66) ~[javafmllanguage-1.20.6-50.1.7.jar!/:50.1.7] {}
		at LAYER PLUGIN/net.minecraftforge.fmlcore@1.20.6-50.1.7/net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$5(ModContainer.java:125) ~[fmlcore-1.20.6-50.1.7.jar!/:1.0] {}
		at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
		at java.base/java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
		at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387) ~[?:?] {}
		at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312) ~[?:?] {}
		at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843) ~[?:?] {}
		at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808) ~[?:?] {}
		at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188) ~[?:?] {}

	Mod File: /home/container/mods/fltpot-1.20.6-0.3.3.jar
	Failure message: Flight Potion (fltpot) has failed to load correctly
		java.lang.NoClassDefFoundError: net/minecraft/client/renderer/entity/RenderLayerParent
	Mod Version: 1.20.6-0.3.3
	Mod Issue URL: https://github.com/DroidDude/fltpot/issues
	Exception message: java.lang.ClassNotFoundException: net.minecraft.client.renderer.entity.RenderLayerParent
Stacktrace:
	at cpw.mods.securejarhandler/net.minecraftforge.securemodules.SecureModuleClassLoader.loadClass(SecureModuleClassLoader.java:454) ~[securemodules-2.2.19.jar!/:?] {}
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?] {}
	at java.base/java.lang.Class.getDeclaredConstructors0(Native Method) ~[?:?] {re:mixin}
	at java.base/java.lang.Class.privateGetDeclaredConstructors(Class.java:3549) ~[?:?] {re:mixin}
	at java.base/java.lang.Class.getConstructor0(Class.java:3754) ~[?:?] {re:mixin}
	at java.base/java.lang.Class.getDeclaredConstructor(Class.java:2930) ~[?:?] {re:mixin}
	at LAYER PLUGIN/net.minecraftforge.javafmlmod@1.20.6-50.1.7/net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:66) ~[javafmllanguage-1.20.6-50.1.7.jar!/:50.1.7] {}
	at LAYER PLUGIN/net.minecraftforge.fmlcore@1.20.6-50.1.7/net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$5(ModContainer.java:125) ~[fmlcore-1.20.6-50.1.7.jar!/:1.0] {}
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387) ~[?:?] {}
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312) ~[?:?] {}
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843) ~[?:?] {}
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808) ~[?:?] {}
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188) ~[?:?] {}


-- System Details --
Details:
	Minecraft Version: 1.20.6
	Minecraft Version ID: 1.20.6
	Operating System: Linux (amd64) version 5.15.0-100-generic
	Java Version: 21.0.3, Eclipse Adoptium
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Eclipse Adoptium
	Memory: 184778560 bytes (176 MiB) / 455081984 bytes (434 MiB) up to 4294967296 bytes (4096 MiB)
	CPUs: 2
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 5 3600 6-Core Processor
	Identifier: AuthenticAMD Family 23 Model 113 Stepping 0
	Microarchitecture: Zen 2
	Frequency (GHz): -0.00
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 12
	Graphics card #0 name: unknown
	Graphics card #0 vendor: unknown
	Graphics card #0 VRAM (MB): 0.00
	Graphics card #0 deviceId: unknown
	Graphics card #0 versionInfo: unknown
	Virtual memory max (MB): 97101.50
	Virtual memory used (MB): 136040.50
	Swap memory total (MB): 32735.00
	Swap memory used (MB): 27329.48
	JVM Flags: 2 total; -Xms128M -Xmx4096M
	ModLauncher: 10.2.1
	ModLauncher launch target: forge_server
	ModLauncher naming: mcp
	ModLauncher services: 
		/ slf4jfixer PLUGINSERVICE 
		/ runtimedistcleaner PLUGINSERVICE 
		/ runtime_enum_extender PLUGINSERVICE 
		/ object_holder_definalize PLUGINSERVICE 
		/ capability_token_subclass PLUGINSERVICE 
		/ accesstransformer PLUGINSERVICE 
		/ eventbus PLUGINSERVICE 
		/ mixin PLUGINSERVICE 
		/ fml TRANSFORMATIONSERVICE 
		/ mixin TRANSFORMATIONSERVICE 
	FML Language Providers: 
		lowcodefml@50
		minecraft@1.0
		javafml@50.1.7
	Mod List: 
		configured-forge-1.20.6-2.4.0.jar                 |Configured                    |configured                    |2.4.0               |COMMON_SET|Manifest: 0d:78:5f:44:c0:47:0c:8c:e2:63:a3:04:43:d4:12:7d:b0:7c:35:37:dc:40:b1:c1:98:ec:51:eb:3b:3c:45:99
		forge-1.20.6-50.1.7-server.jar                    |Minecraft                     |minecraft                     |1.20.6              |COMMON_SET|Manifest: NOSIGNATURE
		kuma-api-forge-20.6.4+1.20.6.jar                  |KumaAPI                       |kuma_api                      |20.6.4              |COMMON_SET|Manifest: NOSIGNATURE
		TerraBlender-forge-1.20.6-3.5.0.5.jar             |TerraBlender                  |terrablender                  |3.5.0.5             |COMMON_SET|Manifest: NOSIGNATURE
		GlitchCore-forge-1.20.6-1.1.0.10.jar              |GlitchCore                    |glitchcore                    |1.1.0.10            |COMMON_SET|Manifest: NOSIGNATURE
		elytrachestplates-1.0.3-forge-1.20.6.jar          |Elytra Chestplates            |elytrachestplates             |1.0.3-forge-1.20.6  |COMMON_SET|Manifest: NOSIGNATURE
		BiomesOPlenty-forge-1.20.6-18.4.0.8.jar           |Biomes O' Plenty              |biomesoplenty                 |18.4.0.8            |COMMON_SET|Manifest: NOSIGNATURE
		oreharvester-1.20.6-1.2.jar                       |Ore Harvester                 |oreharvester                  |1.2                 |COMMON_SET|Manifest: NOSIGNATURE
		mcw-doors-1.1.1forge-mc1.20.6.jar                 |Macaw's Doors                 |mcwdoors                      |1.1.1               |COMMON_SET|Manifest: NOSIGNATURE
		treeharvester-1.20.6-8.9.jar                      |Tree Harvester                |treeharvester                 |8.9                 |COMMON_SET|Manifest: NOSIGNATURE
		mcw-fences-1.1.2-mc1.20.6forge.jar                |Macaw's Fences and Walls      |mcwfences                     |1.1.2               |COMMON_SET|Manifest: NOSIGNATURE
		mcw-trapdoors-1.1.3-mc1.20.6forge.jar             |Macaw's Trapdoors             |mcwtrpdoors                   |1.1.3               |COMMON_SET|Manifest: NOSIGNATURE
		balm-forge-1.20.6-10.3.3-all.jar                  |Balm                          |balm                          |10.3.3              |COMMON_SET|Manifest: NOSIGNATURE
		fltpot-1.20.6-0.3.3.jar                           |Flight Potion                 |fltpot                        |1.20.6-0.3.3        |ERROR     |Manifest: NOSIGNATURE
		forge-1.20.6-50.1.7-universal.jar                 |Forge                         |forge                         |50.1.7              |COMMON_SET|Manifest: NOSIGNATURE
		OverpoweredMending-1.20.6-1.20.6.1.jar            |OverpoweredMending            |overpoweredmending            |1.20.6.1            |COMMON_SET|Manifest: NOSIGNATURE
		waystones-forge-1.20.6-17.0.2.jar                 |Waystones                     |waystones                     |17.0.2              |COMMON_SET|Manifest: NOSIGNATURE
		collective-1.20.6-7.62.jar                        |Collective                    |collective                    |7.62                |COMMON_SET|Manifest: NOSIGNATURE
		mcw-paths-1.0.5-1.20.6forge.jar                   |Macaw's Paths and Pavings     |mcwpaths                      |1.0.5               |COMMON_SET|Manifest: NOSIGNATURE
		mcw-paintings-1.0.5-1.20.6forge.jar               |Macaw's Paintings             |mcwpaintings                  |1.0.5               |COMMON_SET|Manifest: NOSIGNATURE
		mcw-lights-1.1.0-mc1.20.6forge.jar                |Macaw's Lights and Lamps      |mcwlights                     |1.1.0               |COMMON_SET|Manifest: NOSIGNATURE
		whatdurability-1.20.6-1.1.jar                     |What Durability?              |whatdurability                |1.1                 |COMMON_SET|Manifest: NOSIGNATURE
	Crash Report UUID: d98b09fd-38f8-4e24-885e-64b2257da537
	FML: 0.0
	Forge: net.minecraftforge:50.1.7

**Comment by DroidDude** [comment]
Oh, I know what the problem is. It's related to https://github.com/MinecraftForge/MinecraftForge/pull/9891
I'll get to it tomorrow!

**Comment by Refu91** [comment]
Awesome, thank you!
:)

**Comment by DroidDude** [comment]
This should fix the issue.
Thanks for reporting!

**Comment by Refu91** [comment]
Indeed solved!
It works now, thanks alot!
