### ISSUE TITLE
Player gets disconnected when trying to fly on a server.

### ISSUE THREAD

**Issue by DAQEM** [DroidDude/fltpot#2]
[15:41:56] [Server thread/FATAL]: Attempted to load class net/minecraft/client/Minecraft for invalid dist DEDICATED_SERVER
[15:41:56] [Server thread/ERROR]: Exception caught during firing event: Attempted to load class net/minecraft/client/Minecraft for invalid dist DEDICATED_SERVER
        Index: 1
        Listeners:
                0: HIGHEST
                1: ASM: class eu.newaustrianservers.fltpot.event.Events doFlying(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
java.lang.RuntimeException: Attempted to load class net/minecraft/client/Minecraft for invalid dist DEDICATED_SERVER
        at MC-BOOTSTRAP/fmlloader@1.17.1-37.1.0/net.minecraftforge.fml.loading.RuntimeDistCleaner.processClassWithFlags(RuntimeDistCleaner.java:71)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@9.0.7/cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:88)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@9.0.7/cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@9.0.7/cpw.mods.modlauncher.TransformingClassLoader.maybeTransformClassBytes(TransformingClassLoader.java:50)
        at cpw.mods.securejarhandler@0.9.54/cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:110)
        at cpw.mods.securejarhandler@0.9.54/cpw.mods.cl.ModuleClassLoader.lambda$findClass$16(ModuleClassLoader.java:213)
        at cpw.mods.securejarhandler@0.9.54/cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:223)
        at cpw.mods.securejarhandler@0.9.54/cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:213)
        at cpw.mods.securejarhandler@0.9.54/cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:130)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
        at TRANSFORMER/fltpot@1.17.1-0.2.4/eu.newaustrianservers.fltpot.event.Events.doFlying(Events.java:40)
        at net.minecraftforge.eventbus.ASMEventHandler_3_Events_doFlying_PlayerTickEvent.invoke(.dynamic)
        at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85)
        at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.EventBus.post(EventBus.java:302)
        at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.EventBus.post(EventBus.java:283)
        at TRANSFORMER/forge@37.1.0/net.minecraftforge.fmllegacy.hooks.BasicEventHooks.onPlayerPreTick(BasicEventHooks.java:85)
        at TRANSFORMER/minecraft@1.17.1/net.minecraft.world.entity.player.Player.m_8119_(Player.java:207)
        at TRANSFORMER/minecraft@1.17.1/net.minecraft.server.level.ServerPlayer.m_9240_(ServerPlayer.java:429)
        at TRANSFORMER/minecraft@1.17.1/net.minecraft.server.network.ServerGamePacketListenerImpl.m_9933_(ServerGamePacketListenerImpl.java:205)
        at TRANSFORMER/minecraft@1.17.1/net.minecraft.network.Connection.m_129483_(Connection.java:233)
        at TRANSFORMER/minecraft@1.17.1/net.minecraft.server.network.ServerConnectionListener.m_9721_(ServerConnectionListener.java:142)
        at TRANSFORMER/minecraft@1.17.1/net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:897)
        at TRANSFORMER/minecraft@1.17.1/net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServer.java:334)
        at TRANSFORMER/minecraft@1.17.1/net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:819)
        at TRANSFORMER/minecraft@1.17.1/net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:684)
        at TRANSFORMER/minecraft@1.17.1/net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:258)
        at java.base/java.lang.Thread.run(Thread.java:833)

[15:41:56] [Server thread/WARN]: Failed to handle packet for /127.0.0.1:60959
net.minecraft.ReportedException: Ticking player
        at net.minecraft.server.level.ServerPlayer.m_9240_(ServerPlayer.java:492) ~[server-1.17.1-20210706.113038-srg.jar%2326!:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.m_9933_(ServerGamePacketListenerImpl.java:205) ~[server-1.17.1-20210706.113038-srg.jar%2326!:?]
        at net.minecraft.network.Connection.m_129483_(Connection.java:233) ~[server-1.17.1-20210706.113038-srg.jar%2326!:?]
        at net.minecraft.server.network.ServerConnectionListener.m_9721_(ServerConnectionListener.java:142) ~[server-1.17.1-20210706.113038-srg.jar%2326!:?]
        at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:897) ~[server-1.17.1-20210706.113038-srg.jar%2326!:?]
        at net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServer.java:334) ~[server-1.17.1-20210706.113038-srg.jar%2326!:?]
        at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:819) ~[server-1.17.1-20210706.113038-srg.jar%2326!:?]
        at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:684) ~[server-1.17.1-20210706.113038-srg.jar%2326!:?]
        at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:258) ~[server-1.17.1-20210706.113038-srg.jar%2326!:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.RuntimeException: Attempted to load class net/minecraft/client/Minecraft for invalid dist DEDICATED_SERVER
        at net.minecraftforge.fml.loading.RuntimeDistCleaner.processClassWithFlags(RuntimeDistCleaner.java:71) ~[fmlloader-1.17.1-37.1.0.jar%2322!:1.0]
        at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:88) ~[modlauncher-9.0.7.jar%235!:?]
        at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120) ~[modlauncher-9.0.7.jar%235!:?]
        at cpw.mods.modlauncher.TransformingClassLoader.maybeTransformClassBytes(TransformingClassLoader.java:50) ~[modlauncher-9.0.7.jar%235!:?]
        at cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:110) ~[securejarhandler-0.9.54.jar:?]
        at cpw.mods.cl.ModuleClassLoader.lambda$findClass$16(ModuleClassLoader.java:213) ~[securejarhandler-0.9.54.jar:?]
        at cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:223) ~[securejarhandler-0.9.54.jar:?]
        at cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:213) ~[securejarhandler-0.9.54.jar:?]
        at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:130) ~[securejarhandler-0.9.54.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
        at eu.newaustrianservers.fltpot.event.Events.doFlying(Events.java:40) ~[fltpot-1.17.1-0.2.4.jar%2324!:1.17.1-0.2.4]
        at net.minecraftforge.eventbus.ASMEventHandler_3_Events_doFlying_PlayerTickEvent.invoke(.dynamic) ~[?:?]
        at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-5.0.3.jar%232!:?]
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-5.0.3.jar%232!:?]
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-5.0.3.jar%232!:?]
        at net.minecraftforge.fmllegacy.hooks.BasicEventHooks.onPlayerPreTick(BasicEventHooks.java:85) ~[forge-1.17.1-37.1.0-universal.jar%2330!:?]
        at net.minecraft.world.entity.player.Player.m_8119_(Player.java:207) ~[server-1.17.1-20210706.113038-srg.jar%2326!:?]
        at net.minecraft.server.level.ServerPlayer.m_9240_(ServerPlayer.java:429) ~[server-1.17.1-20210706.113038-srg.jar%2326!:?]
        ... 9 more
[15:41:56] [Server thread/INFO]: DaqEm lost connection: Internal server error

**Comment by DroidDude** [comment]
Issue fixed with 0.2.5

**Comment by DroidDude** [comment]
Issue fixed with 0.2.5
